#
# Module manifest for module 'MASES.PLC4NetPS'
#
# Generated by: MASES s.r.l.
#

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = 'MASES.PLC4NetPS.dll'

# Version number of this module.
ModuleVersion = '0.12.0'

# ID used to uniquely identify this module
GUID = '2CC874D6-ADDF-409A-BE3F-E7BF88C98906'

# Author of this module
Author = 'MASES s.r.l.'

# Company or vendor of this module
CompanyName = 'MASES s.r.l.'

# Copyright statement for this module
Copyright = 'Copyright ©  MASES s.r.l. 2025'

# Description of the functionality provided by this module
Description = 'PowerShell Module to use PLC4X and PowerShell side-by-side. With PLC4NetPS it is possible to use PLC4X objects within PowerShell. See https://github.com/masesgroup/PLC4Net for further information.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Specifies the compatible PSEditions of the module.
CompatiblePSEditions = @('Desktop')

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = '4.6.2'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
#FormatsToProcess = ''

# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules= @()

# Functions to export from this module
FunctionsToExport = @()

# Cmdlets to export from this module
CmdletsToExport = @(
    'Start-PLC4NetPS',
    'New-PLCObject'
)

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = @()

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
FileList = ''

# Private data to pass to the module specified in ModuleToProcess
PrivateData = @{

    PSData = @{

        Tags = @('PLC4NetPS', 'PLC4Net', 'PSEdition_Core', 'PSEdition_Desktop', 'Windows', 'Linux', 'JVM', 'Java', 'PLC4X', 'PLC', 'bridge', 'gateway')

        LicenseUri = 'https://github.com/masesgroup/PLC4Net/blob/master/LICENSE'

        ProjectUri = 'https://github.com/masesgroup/PLC4Net'

        IconUri = 'https://raw.githubusercontent.com/masesgroup/PLC4Net/master/src/net/Common/JCOB128x128.png'

        ReleaseNotes = 'https://github.com/masesgroup/PLC4Net/releases'

    }
}

HelpInfoURI = 'https://plc4net.masesgroup.com/articles/usagePS.html'

# DefaultCommandPrefix = ''
}