#
# Module manifest for module 'MASES.PLCOnNetPS'
#
# Generated by: MASES s.r.l.
#

@{

RootModule = 'MASES.PLCOnNetPS.psm1'

ModuleVersion = '0.12.3'

CompatiblePSEditions = 'Desktop', 'Core'

GUID = 'FE6DE86E-0DFB-44E0-A6C6-1604E9A9B7C6'

Author = 'MASES s.r.l.'

CompanyName = 'MASES s.r.l.'

Copyright = 'Copyright ©  MASES s.r.l. 2025'

Description = 'PLCOnNet (.NET suite for PLC4X™) PowerShell (aka PLCOnNetPS) is a PowerShell Module to use PLC4X™ and PowerShell side-by-side. With PLCOnNetPS it is possible to:
- create and use PLC4X™ objects from PowerShell: initialize PLC4X™ object (Java, Scala, Kotlin, ...), execute methods on the object, read data from the object to be used for further PowerShell code 
- send to JVM objects data managed from PowerShell: e.g. data of PowerShell, like an input from command-line or a variable, can be used as an argument for the initialization or execution of a method of a JVM object

More information within the project hosted on GitHub at https://github.com/masesgroup/PLCOnNet for further information.'

PowerShellVersion = '5.1'

# PowerShellHostName = ''

# PowerShellHostVersion = ''

# DotNetFrameworkVersion = ''

# CLRVersion = ''

# ProcessorArchitecture = ''

# RequiredModules = @()

# RequiredAssemblies = @()

# ScriptsToProcess = @()

# TypesToProcess = @()

# FormatsToProcess = @()

# NestedModules = @()

FunctionsToExport = @()

CmdletsToExport = @(
    'Start-PLCOnNetPS',
    'New-PlcUsernamePasswordAuthentication',
    'Get-ProtocolCodes',
    'Get-PlcDriver',
    'Get-PlcConnection',
    'Start-OPCUAServer',
    'Start-Plc4xServer'
)

VariablesToExport = '*'

AliasesToExport = @()

# DscResourcesToExport = @()

# ModuleList = @()

# FileList = @()

PrivateData = @{

    PSData = @{

        Tags = @('PLCOnNetPS', 'PLCOnNet', 'PSEdition_Core', 'PSEdition_Desktop', 'Windows', 'Linux', 'JVM', 'Java', 'PLC4X™', 'PLC', 'IOT', 'bridge', 'gateway')

        LicenseUri = 'https://github.com/masesgroup/PLCOnNet/blob/master/LICENSE'

        ProjectUri = 'https://github.com/masesgroup/PLCOnNet'

        IconUri = 'https://raw.githubusercontent.com/masesgroup/PLCOnNet/master/src/net/Common/JCOB128x128.png'

        ReleaseNotes = 'https://github.com/masesgroup/PLCOnNet/releases'

    }
} 

HelpInfoURI = 'https://plconnet.masesgroup.com/articles/usagePS.html'

# DefaultCommandPrefix = ''
}

